---
driver:
  name: ec2
  aws_ssh_key_id: sfisher-ie
  region: eu-west-1
  availability_zone: b
  instance_type: t2.micro
  security_group_ids: ['sg-50658837']
  retryable_tries: 120

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

transport:
  ssh_key: ~/.ssh/id_rsa

suites:
  - name: default
    run_list:
      - recipe[dafne_online::default]
    attributes:
