---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
    driver:
      network:
        - ["private_network", {ip: "192.168.33.34"}]

suites:
  - name: default
    run_list:
      - recipe[dafne_online::default]
    attributes:
