name 'dafne_online'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures dafne_online'
long_description 'Installs/Configures dafne_online'
version '0.1.0'

depends 'nginx', '~> 2.7.6'
depends 'mysql', '~> 7.1.0'
depends 'mysql2_chef_gem', '~> 1.1.0'
depends 'database', '~> 5.1.2'
depends 'br-ruby', '~> 0.5.2'
